# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lsmon/dev/sst-c-api

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lsmon/dev/sst-c-api

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lsmon/dev/sst-c-api/CMakeFiles /home/lsmon/dev/sst-c-api//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lsmon/dev/sst-c-api/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sst-c-api

# Build rule for target.
sst-c-api: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sst-c-api
.PHONY : sst-c-api

# fast build rule for target.
sst-c-api/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sst-c-api.dir/build.make CMakeFiles/sst-c-api.dir/build
.PHONY : sst-c-api/fast

#=============================================================================
# Target rules for targets named crypto_test

# Build rule for target.
crypto_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crypto_test
.PHONY : crypto_test

# fast build rule for target.
crypto_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test.dir/build.make CMakeFiles/crypto_test.dir/build
.PHONY : crypto_test/fast

src/c_api.o: src/c_api.c.o
.PHONY : src/c_api.o

# target to build an object file
src/c_api.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sst-c-api.dir/build.make CMakeFiles/sst-c-api.dir/src/c_api.c.o
.PHONY : src/c_api.c.o

src/c_api.i: src/c_api.c.i
.PHONY : src/c_api.i

# target to preprocess a source file
src/c_api.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sst-c-api.dir/build.make CMakeFiles/sst-c-api.dir/src/c_api.c.i
.PHONY : src/c_api.c.i

src/c_api.s: src/c_api.c.s
.PHONY : src/c_api.s

# target to generate assembly for a file
src/c_api.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sst-c-api.dir/build.make CMakeFiles/sst-c-api.dir/src/c_api.c.s
.PHONY : src/c_api.c.s

src/c_common.o: src/c_common.c.o
.PHONY : src/c_common.o

# target to build an object file
src/c_common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sst-c-api.dir/build.make CMakeFiles/sst-c-api.dir/src/c_common.c.o
.PHONY : src/c_common.c.o

src/c_common.i: src/c_common.c.i
.PHONY : src/c_common.i

# target to preprocess a source file
src/c_common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sst-c-api.dir/build.make CMakeFiles/sst-c-api.dir/src/c_common.c.i
.PHONY : src/c_common.c.i

src/c_common.s: src/c_common.c.s
.PHONY : src/c_common.s

# target to generate assembly for a file
src/c_common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sst-c-api.dir/build.make CMakeFiles/sst-c-api.dir/src/c_common.c.s
.PHONY : src/c_common.c.s

src/c_crypto.o: src/c_crypto.c.o
.PHONY : src/c_crypto.o

# target to build an object file
src/c_crypto.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sst-c-api.dir/build.make CMakeFiles/sst-c-api.dir/src/c_crypto.c.o
.PHONY : src/c_crypto.c.o

src/c_crypto.i: src/c_crypto.c.i
.PHONY : src/c_crypto.i

# target to preprocess a source file
src/c_crypto.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sst-c-api.dir/build.make CMakeFiles/sst-c-api.dir/src/c_crypto.c.i
.PHONY : src/c_crypto.c.i

src/c_crypto.s: src/c_crypto.c.s
.PHONY : src/c_crypto.s

# target to generate assembly for a file
src/c_crypto.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sst-c-api.dir/build.make CMakeFiles/sst-c-api.dir/src/c_crypto.c.s
.PHONY : src/c_crypto.c.s

src/c_secure_comm.o: src/c_secure_comm.c.o
.PHONY : src/c_secure_comm.o

# target to build an object file
src/c_secure_comm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sst-c-api.dir/build.make CMakeFiles/sst-c-api.dir/src/c_secure_comm.c.o
.PHONY : src/c_secure_comm.c.o

src/c_secure_comm.i: src/c_secure_comm.c.i
.PHONY : src/c_secure_comm.i

# target to preprocess a source file
src/c_secure_comm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sst-c-api.dir/build.make CMakeFiles/sst-c-api.dir/src/c_secure_comm.c.i
.PHONY : src/c_secure_comm.c.i

src/c_secure_comm.s: src/c_secure_comm.c.s
.PHONY : src/c_secure_comm.s

# target to generate assembly for a file
src/c_secure_comm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sst-c-api.dir/build.make CMakeFiles/sst-c-api.dir/src/c_secure_comm.c.s
.PHONY : src/c_secure_comm.c.s

src/ipfs.o: src/ipfs.c.o
.PHONY : src/ipfs.o

# target to build an object file
src/ipfs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sst-c-api.dir/build.make CMakeFiles/sst-c-api.dir/src/ipfs.c.o
.PHONY : src/ipfs.c.o

src/ipfs.i: src/ipfs.c.i
.PHONY : src/ipfs.i

# target to preprocess a source file
src/ipfs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sst-c-api.dir/build.make CMakeFiles/sst-c-api.dir/src/ipfs.c.i
.PHONY : src/ipfs.c.i

src/ipfs.s: src/ipfs.c.s
.PHONY : src/ipfs.s

# target to generate assembly for a file
src/ipfs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sst-c-api.dir/build.make CMakeFiles/sst-c-api.dir/src/ipfs.c.s
.PHONY : src/ipfs.c.s

src/load_config.o: src/load_config.c.o
.PHONY : src/load_config.o

# target to build an object file
src/load_config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sst-c-api.dir/build.make CMakeFiles/sst-c-api.dir/src/load_config.c.o
.PHONY : src/load_config.c.o

src/load_config.i: src/load_config.c.i
.PHONY : src/load_config.i

# target to preprocess a source file
src/load_config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sst-c-api.dir/build.make CMakeFiles/sst-c-api.dir/src/load_config.c.i
.PHONY : src/load_config.c.i

src/load_config.s: src/load_config.c.s
.PHONY : src/load_config.s

# target to generate assembly for a file
src/load_config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sst-c-api.dir/build.make CMakeFiles/sst-c-api.dir/src/load_config.c.s
.PHONY : src/load_config.c.s

tests/c_crypto_test.o: tests/c_crypto_test.c.o
.PHONY : tests/c_crypto_test.o

# target to build an object file
tests/c_crypto_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test.dir/build.make CMakeFiles/crypto_test.dir/tests/c_crypto_test.c.o
.PHONY : tests/c_crypto_test.c.o

tests/c_crypto_test.i: tests/c_crypto_test.c.i
.PHONY : tests/c_crypto_test.i

# target to preprocess a source file
tests/c_crypto_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test.dir/build.make CMakeFiles/crypto_test.dir/tests/c_crypto_test.c.i
.PHONY : tests/c_crypto_test.c.i

tests/c_crypto_test.s: tests/c_crypto_test.c.s
.PHONY : tests/c_crypto_test.s

# target to generate assembly for a file
tests/c_crypto_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test.dir/build.make CMakeFiles/crypto_test.dir/tests/c_crypto_test.c.s
.PHONY : tests/c_crypto_test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... crypto_test"
	@echo "... sst-c-api"
	@echo "... src/c_api.o"
	@echo "... src/c_api.i"
	@echo "... src/c_api.s"
	@echo "... src/c_common.o"
	@echo "... src/c_common.i"
	@echo "... src/c_common.s"
	@echo "... src/c_crypto.o"
	@echo "... src/c_crypto.i"
	@echo "... src/c_crypto.s"
	@echo "... src/c_secure_comm.o"
	@echo "... src/c_secure_comm.i"
	@echo "... src/c_secure_comm.s"
	@echo "... src/ipfs.o"
	@echo "... src/ipfs.i"
	@echo "... src/ipfs.s"
	@echo "... src/load_config.o"
	@echo "... src/load_config.i"
	@echo "... src/load_config.s"
	@echo "... tests/c_crypto_test.o"
	@echo "... tests/c_crypto_test.i"
	@echo "... tests/c_crypto_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

